index:
    path: /
    controller: App\Controller\ClimaController::index
clima_historial:
    path: /historial
    controller: App\Controller\ClimaHistorialController::index
clima_historial_crear:
    path: /historial_crear
    controller: App\Controller\ClimaHistorialController::create